//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica.Backend.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Mascota
    {
        public int ID { get; set; }
        
        public string nombre { get; set; }
        
        public string animal { get; set; }
        
        public int edad { get; set; }
        
        public System.DateTimeOffset fecha { get; set; }
        
        public string descripcion { get; set; }
        
    }
}
